# Generated by Django 3.2 on 2021-05-05 06:55

from django.db import migrations, models

from profanitycustom.extras import ProfanityFilter
#import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1000, validators=[ProfanityFilter]),
        ),
    ]
