# Generated by Django 3.2.6 on 2021-11-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgnotifications', '0005_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
